# Generated by Django 4.0.3 on 2022-04-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_to_category_rel',
        ),
        migrations.AddField(
            model_name='post',
            name='post_to_category_rel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
